// Generated by https://quicktype.io

namespace TransportDisplay.API.Clients
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;

    public partial class Responses
    {
        public partial class HslStopsQueryResponse
        {
            [JsonProperty("data")]
            public Data Data { get; set; }
        }

        public partial class Data
        {
            [JsonProperty("stops")]
            public Stop[] Stops { get; set; }
        }

        public partial class Stop
        {
            [JsonProperty("gtfsId")]
            public string GtfsId { get; set; }
        }
    }
}
