// Generated by https://quicktype.io

namespace TransportDisplay.API.Clients
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;

    public partial class Responses
    {
        public partial class HslTimetableQueryResponse
        {
            [JsonProperty("data")]
            public Data Data { get; set; }
        }

        public partial class Data
        {
            [JsonProperty("stop")]
            public Stop Stop { get; set; }
        }

        public partial class Stop
        {
            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("stoptimesWithoutPatterns")]
            public StoptimesWithoutPattern[] StoptimesWithoutPatterns { get; set; }
        }

        public partial class StoptimesWithoutPattern
        {
            [JsonProperty("scheduledArrival")]
            public long ScheduledArrival { get; set; }

            [JsonProperty("realtimeArrival")]
            public long RealtimeArrival { get; set; }

            [JsonProperty("arrivalDelay")]
            public long ArrivalDelay { get; set; }

            [JsonProperty("scheduledDeparture")]
            public long ScheduledDeparture { get; set; }

            [JsonProperty("realtimeDeparture")]
            public long RealtimeDeparture { get; set; }

            [JsonProperty("departureDelay")]
            public long DepartureDelay { get; set; }

            [JsonProperty("realtime")]
            public bool Realtime { get; set; }

            [JsonProperty("realtimeState")]
            public string RealtimeState { get; set; }

            [JsonProperty("serviceDay")]
            public long ServiceDay { get; set; }

            [JsonProperty("headsign")]
            public string Headsign { get; set; }

            [JsonProperty("trip")]
            public Trip Trip { get; set; }
        }

        public partial class Trip
        {
            [JsonProperty("routeShortName")]
            public string RouteShortName { get; set; }
        }
    }
}
